package main

import (
	"fmt"
	"sort"
	"strings"
)

// renderModule emits trace_check.tla and trace_check.cfg.
//
// The module INSTANCEs twitter.tla rather than restating it. T!Next is the
// model's own transition relation; nothing about the model's semantics is
// re-encoded here, so a bug in this file cannot make an illegal trace look
// legal -- it can only make TLC fail to parse or fail to find the trace.
func renderModule(states []tlaState) (module, cfg string) {
	handles := map[string]bool{}
	var maxTweets, maxTS int64
	for _, s := range states {
		for _, h := range s.KnownUsers {
			handles[h] = true
		}
		if n := int64(len(s.Tweets)); n > maxTweets {
			maxTweets = n
		}
		if s.Clock > maxTS {
			maxTS = s.Clock
		}
	}
	var users []string
	for h := range handles {
		users = append(users, h)
	}
	sort.Strings(users)

	var b strings.Builder
	b.WriteString("-------------------------- MODULE trace_check --------------------------\n")
	b.WriteString(`(***************************************************************************
  GENERATED BY tlclink -- do not edit.

  Forces a behaviour to walk exactly the states an S_obs run produced, while
  requiring every step to satisfy twitter.tla's own Next relation.

  The module INSTANCEs twitter rather than restating it, so the model's
  semantics are never duplicated here.

  Reading the result: this asks TLC to prove the final index is unreachable.
  A reported violation of NotReached means the whole trace was walkable, i.e.
  the link HOLDS. No violation means some step was not a legal model step.
 ***************************************************************************)

EXTENDS Naturals, Sequences, FiniteSets, TLC

CONSTANTS Users, MaxTweets, MaxTimestamp

VARIABLES knownUsers, follows, tweets, clock, nextTweetId, idx

\* Implicit substitution: twitter's CONSTANTS and VARIABLES are all in scope
\* under the same names, so T!Next is the real transition relation.
T == INSTANCE twitter

allVars == <<knownUsers, follows, tweets, clock, nextTweetId, idx>>

`)

	b.WriteString("TraceStates == <<\n")
	for i, s := range states {
		sep := ","
		if i == len(states)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "    %s%s\n", s.record(), sep)
	}
	b.WriteString(">>\n\n")

	b.WriteString(`TraceLen == Len(TraceStates)

AtState(i) ==
    /\ knownUsers  = TraceStates[i].knownUsers
    /\ follows     = TraceStates[i].follows
    /\ tweets      = TraceStates[i].tweets
    /\ clock       = TraceStates[i].clock
    /\ nextTweetId = TraceStates[i].nextTweetId

AtStatePrimed(i) ==
    /\ knownUsers'  = TraceStates[i].knownUsers
    /\ follows'     = TraceStates[i].follows
    /\ tweets'      = TraceStates[i].tweets
    /\ clock'       = TraceStates[i].clock
    /\ nextTweetId' = TraceStates[i].nextTweetId

\* T!Init is asserted here as well as AtState(1): if the first projected
\* state is not the model's initial state, TLC reports no initial states.
Init ==
    /\ idx = 1
    /\ T!Init
    /\ AtState(1)

Next ==
    /\ idx < TraceLen
    /\ T!Next
    /\ AtStatePrimed(idx + 1)
    /\ idx' = idx + 1

Spec == Init /\ [][Next]_allVars

Reached    == idx = TraceLen
NotReached == ~Reached

========================================================================
`)

	var quoted []string
	for _, u := range users {
		quoted = append(quoted, fmt.Sprintf("%q", u))
	}
	cfg = fmt.Sprintf(`SPECIFICATION Spec

CONSTANTS
    Users = {%s}
    MaxTweets = %d
    MaxTimestamp = %d

INVARIANT NotReached
`, strings.Join(quoted, ", "), maxTweets, maxTS)

	return b.String(), cfg
}
