package twitterport.dom

/**
 * VERIFIED CORE. The four observable value types.
 *
 * All four are `data class`es, the Kotlin counterpart of the Java corner's `record`s: structural
 * `equals`/`hashCode` generated by the compiler, so [Edge] can go straight into a `HashSet`
 * without a hand-written pair of methods to get wrong.
 */

/**
 * A single follow edge: [from] follows [to].
 *
 * Deliberately a flat value in one flat set, not a nested `Map<String, Set<String>>`. Finding F004
 * records why: six of the Go store's ten `// @ trusted` shims existed only because the containers
 * were nested, and flattening deleted them outright. The same shape is carried here so the Kotlin
 * corner presents the same small surface.
 */
data class Edge(val from: String, val to: String)

/**
 * One entry of the append-ordered tweet log.
 *
 * [text] is observable but model-irrelevant (D1): the projection used by `tlclink` drops it before
 * checking a trace against `twitter.tla`.
 */
data class Tweet(val id: Long, val author: String, val text: String, val createdAt: Long)

/**
 * A registered user.
 *
 * Ids are allocated from 1 in registration order (D2). Handles are the identity used everywhere in
 * the API; ids are returned but never accepted as input.
 */
data class User(val handle: String, val id: Long)

/**
 * One page of a timeline.
 *
 * [nextCursor] is null exactly when nothing remains below the page (D10), which is the whole
 * meaning of the field: null means precisely "nothing remains", never "unknown". Kotlin's `Long?`
 * states that in the type rather than in a comment -- the Java corner needed a boxed `Long` and a
 * doc paragraph to say the same thing, and nothing stopped a caller from ignoring it.
 */
data class Page(val tweets: List<Tweet>, val nextCursor: Long?)
