package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/michaellady/twitter-port-matrix/tools/internal/implrun"
	"github.com/michaellady/twitter-port-matrix/tools/internal/mutants"
)

func cmdApply(args []string) int {
	fs := flag.NewFlagSet("apply", flag.ExitOnError)
	manifestPath := fs.String("manifest", defaultManifest, "mutant manifest")
	registryPath := fs.String("registry", defaultRegistry, "implementation registry")
	implName := fs.String("impl", "", "implementation name from impls/registry.json")
	id := fs.String("id", "", "mutant id from the catalogue")
	out := fs.String("out", "", "output directory; the mutated tree lands in DIR/tree")
	force := fs.Bool("force", false, "replace an existing mutant directory")
	_ = fs.Parse(args)

	if *implName == "" || *id == "" || *out == "" {
		die("apply needs -impl, -id and -out")
	}
	man, reg := loadAll(*manifestPath, *registryPath)
	m, err := man.Get(*implName, *id)
	if err != nil {
		die("%v", err)
	}
	spec, err := reg.Get(*implName)
	if err != nil {
		die("%v", err)
	}

	if err := prepareOut(*out, *force); err != nil {
		die("%v", err)
	}
	res, err := mutants.Materialize(spec.Dir, m, *out)
	if err != nil {
		die("%v", err)
	}
	regPath, mutantName, err := writeMutantRegistry(*out, spec, m, res)
	if err != nil {
		die("writing registry: %v", err)
	}

	fmt.Printf("mutate apply: %s\n", m.Key())
	fmt.Printf("  family      %s\n", m.Family)
	fmt.Printf("  what        %s\n", m.Description)
	fmt.Printf("  source      %s\n", res.SourceDir)
	fmt.Printf("              base %s\n", res.SourceHash)
	fmt.Printf("  mutant tree %s  (copy mode: %s)\n", res.TreeDir, res.CopyMode)
	fmt.Printf("              tree %s\n", res.TreeHash)
	fmt.Printf("  edits       %d\n", len(res.Edits))
	for _, e := range res.Edits {
		fmt.Printf("                %s:%d  %d bytes -> %d bytes\n", e.File, e.Line, e.WasBytes, e.NowBytes)
	}
	fmt.Printf("  registry    %s\n", regPath)
	fmt.Println()
	fmt.Println("  the rungs can be pointed at it directly:")
	fmt.Printf("    go run ./tools/cmd/replay  -impl=%s -registry=%s\n", mutantName, regPath)
	fmt.Printf("    go run ./tools/cmd/diffrun -impls=%s -registry=%s\n", mutantName, regPath)
	fmt.Println()
	fmt.Println("  the original implementation is untouched; verify with")
	fmt.Printf("    git -C %s status --short\n", res.SourceDir)
	return 0
}

// prepareOut refuses to write over a directory that is not already a mutant
// directory, even with -force. `-out` is going to be passed a scratch path by
// a calibration workflow; a typo there must not delete something else.
func prepareOut(dir string, force bool) error {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return os.MkdirAll(dir, 0o755)
	}
	if err != nil {
		return err
	}
	if len(entries) == 0 {
		return nil
	}
	if _, err := os.Stat(filepath.Join(dir, "mutant.json")); err != nil {
		return fmt.Errorf("%s is not empty and does not look like a mutant directory (no mutant.json); refusing to touch it", dir)
	}
	if !force {
		return fmt.Errorf("%s already holds a mutant; pass -force to replace it", dir)
	}
	return os.RemoveAll(dir)
}

// writeMutantRegistry emits a registry the existing rungs can consume without
// modification.
//
// Both entries are written: the mutant AND the unmutated corner, with absolute
// directories so the file works from any working directory. A rung run against
// a mutant is only interpretable next to the same rung run against the
// original, so the pair travels together.
func writeMutantRegistry(outDir string, spec implrun.Spec, m mutants.Mutant, res *mutants.Result) (string, string, error) {
	baseDir, err := filepath.Abs(spec.Dir)
	if err != nil {
		return "", "", err
	}
	mutantName := m.Impl + "@" + m.ID

	baseline := spec
	baseline.Dir = baseDir

	mutated := spec
	mutated.Dir = res.TreeDir
	mutated.Status = fmt.Sprintf("MUTANT %s (%s): %s -- tree %s",
		m.Key(), m.Family, m.Description, res.TreeHash)

	out := implrun.Registry{
		Note: fmt.Sprintf(
			"Generated by `mutate apply` at %s. %q is a mutated copy of %q; the original under impls/ was never written to. Mutant tree hash %s.",
			time.Now().UTC().Format(time.RFC3339), mutantName, m.Impl, res.TreeHash),
		Impls: map[string]implrun.Spec{
			m.Impl:     baseline,
			mutantName: mutated,
		},
	}
	b, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return "", "", err
	}
	path := filepath.Join(outDir, "registry.json")
	if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
		return "", "", err
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", "", err
	}
	return abs, mutantName, nil
}
